name: Deploy to production

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Nuxt app
        run: npm run build

      - name: List contents of .output directory
        run: ls -R .output

      - name: Upload to production
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: .output/*
          target: /var/www/temp

      - name: Install pm2
        run: npm install -g pm2

      - name: Clean and restart server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            rm -rf /var/www/frontend
            mkdir /var/www/frontend
            mv /var/www/temp/.output/* /var/www/frontend
            pm2 restart /var/www/ecosystem.config.cjs
            rm -rf /var/www/temp
        
      
